### PR TITLE
Add canonical link headers to Haddock-generated documentation pages.

### PR DESCRIPTION
**Pull request by dzackgarza**
Referenced in a few threads, see
https://github.com/haskell/hackage-server/issues/284#issuecomment-67741796
and 
https://github.com/haskell/hackage-server/issues/366#issuecomment-107097816

This should help move search engine results away from specific versions of doc pages (and particularly old/deprecated versions) to their unversioned counterparts. 

Google supports using canonical links in response headers (see <https://support.google.com/webmasters/answer/139066?hl=en#6>), so this patch adds these headers to all requests for rendered doc pages.

For example, a request for
`http://hackage.haskell.org/package/AC-BuildPlatform-1.1.0/docs/System-Platform.html`

should generate the following header in the response:
`Link <http://hackage.haskell.org/package/AC-BuildPlatform/docs/System-Platform.html>; rel="canonical"`

which should always redirect to the latest version.

### CODE REVIEW

**Comment by dcoutts** [comment]
Great!

BTW, I'll probably merge the three patches together because the final result is a good simpler than the intermediate states. Or you can do that if you prefer.

**Comment by dzackgarza** [comment]
Sounds good! I went ahead and squashed everything into one commit.

**Comment by dzackgarza** [comment]
Closed and reopened to trigger a new TravisCI build

**Comment by dcoutts** [comment]
Great.

**Pull request merged**
