### PR TITLE
Night mode fixes

### PR DESCRIPTION
**Pull request by peterbecich**
Night mode fixes

### CODE REVIEW

**Comment by peterbecich** [comment]
looking at https://github.com/haskell/haddock/issues/790#issuecomment-831378596

**Comment by peterbecich** [comment]
looking at https://discourse.haskell.org/t/populate-module-documentation-in-local-instance-of-hackage-server/4630

**Comment by gbaz** [comment]
Right. just build a doc tarball with quickjump enabled, then upload it.

**Comment by peterbecich** [comment]
Big improvement, @gbaz please review

Screenshot 2023-01-06 at 20-49-56 steeloverseer

Screenshot 2023-01-06 at 20-50-27 steeloverseer

**Comment by gbaz** [comment]
Also testing this on prod. Looks much better! Still not perfect, imho -- the light blue of the shortcut keys isn't great, and the highlighting when mousing-over a search result washes out the light text. However, its certainly much more usable than before. Now that we have this and the other set of changes on prod, I think the immediate urgency has passed. I'd certainly like to see some future work to make this really nice, based on your own (good) taste and user feedback, but there's no rush, and its around midnight my time, so I certainly don't intend to think about this fir the next little bit :-) Cheers!

**Comment by peterbecich** [comment]
@gbaz , agreed, I will improve it further later. Thank you for your critical assistance and project leadership! Have a great weekend

**Comment by peterbecich** [comment]
Closes: https://github.com/haskell/hackage-server/issues/1167

I could not reproduce this issue with the Firefox dev tools, but probably fixed by https://github.com/haskell/hackage-server/pull/1163/commits/a9ca79c613e936220283c211291da9ebae9cf18d

Could be further improved: https://stackoverflow.com/questions/7187569/difference-in-applying-css-to-html-body-and-the-universal-selector

Screen Shot 2023-01-28 at 16 07 29

Screenshot 2023-01-28 at 16-10-51 Introduction Hackage


Screenshot 2023-01-28 at 16-07-57 Introduction Hackage

**Comment by peterbecich** [comment]
@gbaz , can we merge this now to close https://github.com/haskell/hackage-server/issues/1167 and make the other fixes https://github.com/haskell/hackage-server/pull/1163#issuecomment-1374382852 later?

**Review by andreasabel — APPROVED** [review]

**Comment by andreasabel** [comment]
@peterbecich : Are these commits self-contained and should be preserved, or should we squash&merge them?

**Comment by peterbecich** [comment]
@andreasabel , squash would be good

**Pull request merged**
