### PR TITLE
Relax aeson dependency, fix #73

### LINKED ISSUE #73: Import client does not work when using aeson-0.6.2
This is because `deriveJSON` in `aeson-0.6.2` generates instances which are incompatible with those generated by `aeson-0.6.1` and the import client generates some JSON by hand (there might be other places where we manually construct JSON too).

### PR DESCRIPTION
**Pull request by DanielG**
I haven't actually tested this since I don't know exactly what was broken by aeson >= 0.6.2.0.

According to https://github.com/bos/aeson/issues/141#issuecomment-24300068 this should fix #73 though.

### CODE REVIEW

**Comment by dcoutts** [comment]
Ok, so according to [bas and bos's comments](https://github.com/bos/aeson/issues/141#issuecomment-24300068) we can change how we use `deriveJSON` to give us compatible JSON output using later versions of aeson, and that way upgrade to the latest aeson (which fixes other issues).

This should be easy to go through and change all the TH deriving instances to use the trick mentioned. Same issue in #73.

**Comment by DanielG** [comment]
Um.. that is exactly what this patch already does. I just don't know how to test if this works as I have no idea exactly where the JSON is even used.

**Comment by dcoutts** [comment]
Ohhhh. Doh. When I originally read this ticket I only looked at the conversation and assumed from the title that it just changed the deps without doing anything else. Too much skim-reading. Sorry.

Yes, with the stuff that bas and bos suggest (which indeed you link to in the original comment) then it should be fine. I'm happy with that, and with assuming that what bas suggests has been well enough tested by other people so we don't need any extra tests ourselves.

**Comment by dcoutts** [comment]
In fact, we could require a rather more recent version, and drop the #ifdefs for the aeson 0.6.1 compat stuff.

**Comment by dcoutts** [comment]
@DanielG thanks for your patience ans apologies for my stupidity.

**Pull request merged**
