### PR TITLE
improve default repo rendering for unknown repos, add pijul rendering

### LINKED ISSUE #238: bad rendering of source repo data for hfuse
https://hackage.haskell.org/package/HFuse

```
head: SourceRepo {repoKind = RepoHead, repoType = Just (OtherRepoType "head"), repoLocation = Just "https://github.com/toothbrush/hfuse.git", repoModule = Nothing, repoBranch = Nothing, repoTag = Nothing, repoSubdir = Nothing}
```

### PR DESCRIPTION
**Pull request by gbaz**
Resolves #238 #646

### CODE REVIEW

**Comment by hvr** [comment]
@gbaz do you happen to have a screenshot share (for convenience) ? :-)

**Comment by gbaz** [comment]
this repo stanza
```

source-repository head
    type: somevcs
    location: http://somerepo.com
    branch: abranch
    tag: atag

```

gets rendered as 

image

**Comment by gbaz** [comment]
which is maybe not lovely, but certainly better than just a `show` of a record :-)

**Comment by hvr** [comment]
This is for the non-candidate view only?

**Comment by gbaz** [comment]
ugh, yeah i didn't backport it to the other file. We really need to disentangle the two and get rid of the non-template path. Shall I backport it, or do we not care until such point as they're merged properly?

**Comment by hvr** [comment]
@gbaz well, I guess we don't need to care much, since this would only affect people deliberately setting exotic source-repo types when looking at candidates...

**Pull request merged**
