### PR TITLE
terrible 'fix' to build failure

### PR DESCRIPTION
**Pull request by jameshfisher**

### CODE REVIEW

**Comment by jameshfisher** [comment]
I have no idea how this builds for other people.

**Comment by bergmark** [comment]
The reason this broke is that happstack-server used to import the terrible `Show (a -> b)` orphan from `Text.Show.Functions` but it no longer does as of a recent release.

**Comment by dcoutts** [comment]
Do we need this Show instance at all? Can we just drop it?

**Comment by dcoutts** [comment]
@jameshfisher @bergmark Thanks. I'll apply @hvr's PR for this #492

**Pull request closed without merging**
