### PR TITLE
Update max cabal-version check to 3.6

### PR DESCRIPTION
**Pull request by ffaf1**
Also add a more informative comment and abstract check/error message.

### CODE REVIEW

**Review by Mikolaj — APPROVED** [review]
LGTM

**Comment by Mikolaj** [comment]
Though

```
src/Distribution/Server/Packages/Unpack.hs:222:54: error:
    • Variable not in scope:
        showCabalSpecVersion :: CabalSpecVersion -> [()]
    • Perhaps you want to add ‘showCabalSpecVersion’ to the import list
      in the import of ‘Distribution.CabalSpecVersion’
      (src/Distribution/Server/Packages/Unpack.hs:(23,1)-(24,33)).
```

**Comment by ulysses4ever** [comment]
Why not 3.8? i don't think it's a good reason to hold back package authors. If a user doesn't have a recent enough cabal, they should have a choice: either update their cabal or not use the package (version). It's absolutely nonsensical to me to forbid package authors to upload such packages — it should be a user's choice.

**Comment by ffaf1** [comment]
Which `cabal` do I need to use `cabal-version: 3.8`? A line has to be drawn somewhere

**Comment by ulysses4ever** [comment]
The principle of least surprise would suggest to use the same version as the Cabal library. Every package page show you which Cabal library version is used by Hackage (see example below). Naturally, people would expect that the same version is the maximum that you can put in your cabal file...
Screenshot_20230622-181507

**Pull request merged**
