### PR TITLE
Add preferred package JSON format handler

### PR DESCRIPTION
**Pull request by potomak**
Example response:

```js
{
  "deprecated-version": ["0.1.0"],
  "unpreferred-version": ["0.2.0"],
  "normal-version": ["0.3.0", "0.3.1"]
}
```

### CODE REVIEW

**Comment by hvr** [comment]
This is *almost* what I need for `hackage-cli` (and other tooling I'm working on) to avoid scraping the package content HTML page... :)

...have you seen #338? I don't think we need to split up all information provided in `/package/:package` into several micro-endpoints. I'd rather expect an `/package/:package.:format` endpoint providing more information; For instance, I need to know for each single version what the highest `x-revision` is, as well when the tarball was uploaded, whether a documentation tarball is available. Splitting that information into several sub-endpoints would require a lot of HTTP GET traffic to reconstruct what `/package/:package.html` already provides now...

**Comment by hvr** [comment]
PS: I'm not saying that this endpoint shouldn't become JSON aware, since it's just an enhancement of an existing one...

**Comment by potomak** [comment]
@hvr I agree, and yes, maybe this could just be another format of the resource `/package/:package/preferred` waiting for an implementation of the handler that responds to `/package/:package` JSON requests.

**Comment by potomak** [comment]
What do you think about adding this handler to the preferred versions feature, to support the JSON format @gracenotes?

**Comment by dcoutts** [comment]
@potomak @hvr yes, providing a .json at the main package page is a good idea, but a bigger undertaking. I'm happy to merge this as is for now.

**Comment by potomak** [comment]
@dcoutts thanks. How can I get notified about the deployment of this feature?

**Comment by dcoutts** [comment]
@potomak missed the deployment window yesterday, but aiming to do it this evening instead.

**Pull request merged**
