### PR TITLE
Add OpenGraph metadata for package pages

### LINKED ISSUE #912: Open Graph description is outdated on package pages
The `og:description` meta tag recommends using `cabal install package-name` for installing packages.
https://github.com/haskell/hackage-server/blob/4039daa37203c1db08c7053ae2751bcf24ae0674/datafiles/templates/Html/package-page.html.st#L15-L16
As of Cabal 3.0 with the new v2-* commands being default this is no longer the recommended way to install packages. It might confuse new Haskell users who see Discord embeds still recommending to use `cabal install` to install dependencies, a matter that already trips them up.
I'm not sure what should be put here instead, suggestions?

### PR DESCRIPTION
**Pull request by MorrowM**
Fixes #912, and adds the functionality to `master`.

### CODE REVIEW

**Comment by Kleidukos** [comment]
Regarding `og:description`, it is supposed to be "one or two sentences" ([_og:description - A one to two sentence description of your object_](https://ogp.me/)). We do not enforce this in the `description` field, and it feels more appropriate that we fill the metadata with the synopsis.

**Comment by MorrowM** [comment]
Good point.
I also thought of having an `og:image` field with the Hackage logo, but I couldn't get it to display, even after making a png (apparently OpenGraph doesn't support svg).

**Comment by gbaz** [comment]
looks good!

**Comment by Kleidukos** [comment]
@MorrowM I think this would be a nice idea but I'll let @gbaz have the last word on this ;)

**Pull request merged**
