### PR TITLE
Auth key docs

### PR DESCRIPTION
**Pull request by agrafix**

### CODE REVIEW

**Comment by dcoutts** [comment]
Merged the doc change. Hopefully the other fix is unnecessary now.

**Comment by dcoutts** [comment]
@agrafix FYI, this is all now deployed, but there's an issue with our CDN that is blocking use of this for the moment. I added an extra protection to stop the api key auth being used over plain http (since like basic auth it's not secure to do that). However the way this check interacts with our CDN is blocking its use for the moment.

**Comment by agrafix** [comment]
@dcoutts okay, cool :-) Let me know when the issue with the CDN is resolved then it probably makes sense to talk to the travis guys to update the hackage plugin. Also all the tools like `cabal` and `stack` would only need your username + password once and can then store and use the token.

**Comment by hvr** [comment]
@agrafix actually that would be less secure than what cabal does now, since api-key is weaker than digest-auth; so we surely don't want cabal to use api-keys instead

**Comment by agrafix** [comment]
@hvr if they go via HTTPS then they should be equally secure?

**Comment by hvr** [comment]
@agrafix only if https was done properly (trusted ssl termination, trusted ssl libraries, proper ssl configuration, trusted CAs and/or trusted certificate, ...). But we're not doing it properly currently, so digest auth is still preferable over basic auth. And tbh, I'm not happy with digest auth either. This is all quite unsatisfying, and this X-ApiKey feature in its current design is quite worrying to me from a security POV; it should only be used for non-critical operations (which would exclude uploading packages as non-candidates IMO).

**Comment by agrafix** [comment]
@hvr I partially agree. The reason I introduces the `X-ApiKey` feature is because to me it just doesn't seem like a good idea to give your username and your password to Travis & co and storing it in plaintext on your machine in the cabal config file seems like a bad idea to me too. Every service and every machine should use it's own token via `X-ApiKey` that can be revoked easily. The next step for the tokens should be a possibility to restrict them, eg. that a certain token can only update package `foobar`.

**Comment by agrafix** [comment]
By the way: we might be able to send the `X-ApiKey` via digest-auth too?

**Comment by hvr** [comment]
We'd have to limit sending the X-ApiKey creds via digest-auth only to do this properly.  Don't take this personally, but this happens to be a pet peeve of mine and X-ApiKey in its current design makes me feel uneasy.

I'd like to see hackage-server hardened over time, and X-ApiKey in principle is a good idea, I just disagree strongly with its current implementation. As this makes me feel so uneasy that I'm loosing sleep over it,  I've filed #541 and I'm prepared to invest time to implement this myself (as I've already implemented similar schemes myself) if you don't have time to implement this yourself.

**Pull request closed without merging**
