### PR TITLE
Revision feed

### PR DESCRIPTION
**Pull request by gbaz**
This sits on top of the earlier pull request for ghc 710 compat. Hope that's ok.

This leverages the existing recent uploads stuff to also track recent cabal metadata revisions and provide that as a webpage and rss feed. Tools that try to stay up to date across all hackage changes should potentially find this useful...

### CODE REVIEW

**Comment by dcoutts** [comment]
Nice. @hvr will be happy.

**Comment by gbaz** [comment]
@acowley too :smile:

**Comment by hvr** [comment]
:joy_cat:

**Comment by gbaz** [comment]
So as per discussions with @hvr, I think making the feed give either 40 entries or the last 48 hours, whichever is greater, would work. I've got work in progress to do this for both the revisions feed and the recent uploads feed. (While leaving the html pages as is). I think this is better than a configurable override, among other reasons, because it means we can do this with the existing caching architecture.

**Pull request merged**
