### PR TITLE
Add server time to tarball timestamp error.

### LINKED ISSUE #480: Uploading of packages from the future
I just created a source tar-ball on my system and tried to upload it. I was greeted with this:

hackage-future-time-error

The time recorded in the tar-ball is completely correct, because well, that *is* the current time. So the question is what time the server thinks it is.

I ended up waiting a few minutes and then retried the upload. That succeeded on the third attempt.

I would have loved if that error page included the time the server has, so I quickly can determine how long I need to wait.

### PR DESCRIPTION
**Pull request by magthe**
The wording of the error is most likely not good, and suggestions for improvements are more than welcome.

### CODE REVIEW

**Comment by magthe** [comment]
The wording of the error is most likely not good, and suggestions for improvements are more than welcome.

**Comment by dcoutts** [comment]
@magthe thanks!

Suggestion for the wording:

> The tarball entry  foo/bar has a file timestamp that is in the future (2016-06-08 00:24:55 UTC vs this server's current time of 2016-06-08 00:23:18 UTC). This tends to cause problems ...

**Comment by magthe** [comment]
@dcoutts Thanks for the suggestion! Updated and force-pushed.

**Comment by andrewufrank** [comment]
thank you for improved error message!

**Pull request merged**
