### PR TITLE
support for `prefers-color-scheme`

### PR DESCRIPTION
**Pull request by peterbecich**
Closes https://github.com/haskell/hackage-server/issues/1007
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Some of the foreground and background colors are simply swapped. ~`href` colors should probably be brightened.~ Opinions appreciated. Preview: https://github.com/haskell/hackage-server/pull/1008#issuecomment-1138132085

### CODE REVIEW

**Comment by peterbecich** [comment]
2x brightness for captions and links:
https://github.com/haskell/hackage-server/blob/80c4f95d6ff87fb242058f33724bcd90491bcc8b/datafiles/static/hackage.css#L83
Screenshot 2022-02-15 at 19-23-15 Introduction Hackage

**Comment by peterbecich** [comment]
Feedback appreciated


Screenshot 2022-05-25 at 21-04-49 Introduction Hackage
Screenshot 2022-05-25 at 21-04-20 Browse and search packages Hackage


How do I populate the module documentation / function definitions? i.e.
```
TwoCaptcha

    TwoCaptcha.Captcha
    Internal
        TwoCaptcha.Internal.Client
        Types
 ...          
```
I should check the function definitions look okay.

Screenshot 2022-05-25 at 21-04-35 2captcha

**Comment by peterbecich** [comment]
Here is the Paginator
Screenshot 2022-05-25 at 23-05-45 Browse and search packages Hackage
Screenshot 2022-05-25 at 23-06-13 Browse and search packages Hackage

**Comment by andreasabel** [comment]
I like the colors and everything is clearly readable.

**Comment by peterbecich** [comment]
One thing I've not checked are any function definitions like:
Screenshot 2022-05-28 at 00-25-54 Data Vector Generic


because on my local instance of Hackage these are unpopulated:
func_definitions


Can you tell me how to populate these?

**Comment by gbaz** [comment]
For the most part people seem really happy about this!

However, a comment points out a few missed spots -- quickjump, and also the (new) revdeps feature. A pr to fix these up would be most welcome. https://discourse.haskell.org/t/new-hackage-server-features/2621/28

**Comment by gbaz** [comment]
oh some of the banners too https://twitter.com/qnikst/status/1611392984700055552

**Comment by peterbecich** [comment]
Whoops, I'll prioritize an opt-in button, will try to get this done today

**Comment by gbaz** [comment]
In my opinion, an opt-out is not so important, compared to just fixing up the maybe three cases discovered so far that need to be handled. Luckily as this is just a CSS change, deploying it will be safe and simple.

**Comment by peterbecich** [comment]
Okay, will do

**Comment by peterbecich** [comment]
WIP https://github.com/haskell/hackage-server/pull/1162 more to go

**Pull request merged**
