### PR TITLE
short package desc check

### PR DESCRIPTION
**Pull request by gbaz**
Check for short package descs as per https://github.com/haskell/cabal/pull/3479

The version of the check via cabal won't make it into hackage for some time, but this is worth getting in place for hackage proper sooner.

### CODE REVIEW

**Comment by gbaz** [comment]
@hvr do we want to get this deployed soon too?

**Comment by Kleidukos** [comment]
@gbaz Do you need anything to land this PR?

**Comment by gbaz** [comment]
I think this just got lost in the weeds.

**Comment by gbaz** [comment]
Actually wait i'm pretty sure this is superceded by it being resolved  upstream in cabal (in the linked ticket). The server checks are additional checks on top of the cabal checks.

**Pull request closed without merging**
