### PR TITLE
Stylesheet revamp

### PR DESCRIPTION
**Pull request by gbaz**
Should supercede #648

### CODE REVIEW

**Comment by gbaz** [comment]
example screenshot:
image

**Comment by gbaz** [comment]
Added the two-col changes on top of this since they were very popular

image

**Comment by gbaz** [comment]
(note: this version is responsive. when the window drops below 980, it falls back to one-column with the properties table following the description, as before)

**Comment by gbaz** [comment]
Pushing a change to get the dependencies to align nicely: 
image

**Comment by mikeplus64** [comment]
I might be alone here, but I much prefer the current colour scheme. The new fonts look good and layout changes are welcome, but to me, the orange links in the older theme stand out much better. This IMO degrades readability. Maybe I am just luddite, but I also just don't 'like' the choice of purple...

This is so clearly subjective that maybe it's a good idea to have the option in Hackage to switch between some "agreed upon" stylesheets? We used to be able to switch between the gloriously ugly :-) (and old) "Ocean" theme and the relatively new and fancy current one, which was pretty nice.

**Comment by ocramz** [comment]
image

The dependencies don't seem to align properly

**Comment by fredefox** [comment]
@ocramz As I understand it, this is the default behavior when multiple deps fit in one line.

**Comment by gbaz** [comment]
This is by design. Each unit between each comma is nonbreaking now.

**Comment by Profpatsch** [comment]
@gbaz For https://hackage.haskell.org/package/git-annex the right column kind of breaks.

For 125% it sometimes starts scrolling to the right: https://github.com/haskell/haddock/pull/721#issuecomment-374914421

**Comment by gbaz** [comment]
What is the issue with git-annex? Just the sea of version numbers? 

For https://hackage.haskell.org/package/abeson the problem is the long name/email address with no whitespace to break on. It could be given the `word-wrap` style but then email addresses in general would break between any two characters, even when a proper whitespace break was possible, which also seems unfortunate, and would affect far more pages. Not sure about the right solution.

**Pull request merged**
