### PR TITLE
allow cc0 in older cabal files

### PR DESCRIPTION
**Pull request by gbaz**
cf haskell/cabal#5238

### CODE REVIEW

**Comment by phadej** [comment]
`cabal-version` is parsed always first.

**Comment by hvr** [comment]
The thing I was worried was (and which Oleg confirmed to me), is that e.g. `version:1.12` + `license: CC0-1.0` won't be mapped to the proper SPDX type, and end up as `LicenseRef:CC0-1.0`   if we don't handle this hardwired exception in `lib:Cabal` proper.

**Comment by phadej** [comment]
We could change licenseTo Spdx to try to parse UnknownLicense, PVP-wise it might be just "new feature", not "breaking change"

**Comment by gbaz** [comment]
> The thing I was worried was (and which Oleg confirmed to me), is that e.g. version:1.12 + license: CC0-1.0 won't be mapped to the proper SPDX type, and end up as LicenseRef:CC0-1.0 if we don't handle this hardwired exception in lib:Cabal proper.

@hrv what would be the consequences of this for hackage? would it just mess up other elements of the UI/display?

**Comment by hvr** [comment]
@gbaz I'm not sure; I'm generally worried that having `licence: CC0-1.0` map to two different things (rather than the unique exact meaning) may result in weirdness down the road. I'll trust @phadej judgement whether it's a problem for lib:Cabal to have these "degenerate licence levels"... :-)

**Comment by gbaz** [comment]
superseded by: https://github.com/haskell/hackage-server/commit/af9096e00bf251c6919e568b0d12441e6715cb65

**Pull request closed without merging**
