### PR TITLE
Add package links to "changelog not found" page

### PR DESCRIPTION
**Pull request by JustRoxy**
One link to its hackage page and another one to package home, if available.

### CODE REVIEW

**Comment by dpwiz** [comment]
@gbaz :musical_note:

**Comment by gbaz** [comment]
Can you motivate this a bit? Isn't the package homepage always linked anyway?

**Comment by dpwiz** [comment]
Not if there's no changelog: https://hackage.haskell.org/package/tracing-0.0.6.0/changelog

**Comment by gbaz** [comment]
Ok, but there's no link to that missing page from https://hackage.haskell.org/package/tracing-0.0.6.0 -- so I don't see how one ends up in this situation?

**Comment by sjakobi** [comment]
I think the background might be that issues on the Stackage issue tracker include a link to the changelog, no matter whether the changelog actually exists. See e.g. https://github.com/commercialhaskell/stackage/issues/5968#issue-843951892.

(I'm actually the author of [this little ergonomic improvement](https://github.com/commercialhaskell/curator/pull/12).)

So I think the proposed link would be very useful for Stackage maintainers including myself. I also don't see any downside?!

**Comment by dpwiz** [comment]
Another one is a [fediverse bot](https://functional.cafe/@hackage) that includes changelog link unconditionally.

**Comment by gbaz** [comment]
Thanks for the context! I just wanted to be sure I understood the motivation before merging, or if any unconditional links existed in hackage itself we should be worried about fixing. Happy to merge now.

**Pull request merged**
