### PR TITLE
Fixes #310: Add build target in Revision

### LINKED ISSUE #310: Show which build-target a change refers to
In the example at

  https://hackage.haskell.org/package/io-streams-1.1.4.3/revisions/

it looks as if the very same change was performed twice, while it was performed in two different parts of the cabal file.

### PR DESCRIPTION
**Pull request by rabisg**
I was working on this but somehow I could not modify any cabal file that I had uploaded in my local version. Can anyone help me regarding the same?

### CODE REVIEW

**Comment by dcoutts** [comment]
@rabisg I think the issue you're seeing is something I fixed earlier today d3431bf85e69399ee80e4e04d952ff02bc25fe7d. I had it reported to me. It was an issue arising out of updating to Cabal-1.22.

**Comment by dcoutts** [comment]
BTW, so far the patch looks good. If it's easy, perhaps we should include the actual exe name, not just the kind.

Perhaps the easiest way to do that would be to reuse the `ComponentName` from Cabal. See https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/LocalBuildInfo.hs#L184

You'd make a the `Component` and use `componentName`, and then in the errors and changes you'd use `showComponentName`.

**Comment by bergmark** [comment]
@rabisg are you planning on implementing Duncan's s suggestion?

**Comment by rabisg** [comment]
Yes I am. I will look into it asap

**Comment by bergmark** [comment]
Thank you!

**Comment by rabisg** [comment]
Updated. If you want I can squash the two commits.

**Comment by dcoutts** [comment]
Great. I'll pull it in test it and squash.

**Pull request merged**
