### PR TITLE
Add lastVersion in listings (#749)

### PR DESCRIPTION
**Pull request by blackheaven**

### CODE REVIEW

**Comment by blackheaven** [comment]
is there anything I can do/improve to get it merged?

**Comment by andreasabel** [comment]
> is there anything I can do/improve to get it merged?

If you ask like this, the answer is yes.
Replace your empty description by:
- motivation of the change
- description of the change
- screenshot to illustrate UI change (if any)
- migration guide for API change (if any)

**Comment by gbaz** [comment]
While that's good general advice, in this case I think its pretty clear with this PR (though a nice description is always helpful!). I'm going to try to get to a bunch of outstanding hackage PRs this holiday season.

**Comment by andreasabel** [comment]
@gbaz wrote:
> I'm going to try to get to a bunch of outstanding hackage PRs this holiday season.

Excellent!

**Comment by gbaz** [comment]
tested locally and doesn't appear to work

image

**Comment by blackheaven** [comment]
Sorry, I've pushed the fix

image

**Comment by gbaz** [comment]
works, thanks!

**Comment by ysangkok** [comment]
@blackheaven 
seems like lastVersion is not updated on package addition: [packageChangeHook](https://github.com/haskell/hackage-server/blob/4d0bd17b1b90f495b59d3e3a6e88e04411b78024/src/Distribution/Server/Features/PackageList.hs#L135)
 
if you upload a new package version , the new version isn't show in the browse listing. This can be reproduced using the instructions in #1168. 

Seem like  `itemLastVersion` should be updated in addition to `itemLastUpload`, would you agree?

**Comment by blackheaven** [comment]
Hello,

It seems so, do you want to push the fix yourself, or can I handle it?

**Comment by ysangkok** [comment]
@blackheaven you feel free to handle it!

**Pull request merged**
