### PR TITLE
Detailed dependency view

### PR DESCRIPTION
**Pull request by grayjay**
I started adding a detailed package dependency view as @dcoutts suggested.  This pull request isn't finished, because I wanted to ask for feedback before I got too far.  The detailed dependencies are temporarily displayed under the original dependencies on the main package page.  This view is only a summary of the .cabal file.  For example, it only displays branches that contain a build-depends or buildable field.  I have some questions about future changes:

* Where should the details go?  Should we add an expander on the main package page so that users can toggle between the short and long dependency views?  I'm not very familiar with generating webpages, so I would need help implementing this.  We could instead link to a new page.
* If the detailed view has its own page, should we modify the flags section, too?  The main page could show only manual flags, and the detailed view could show the full table of flags.
* Should we add any other fields to the detailed view?  I included `buildable` when it is false, because it explains why some branches have no dependencies.
* I copied the formatting from the module tree.  I'm not sure if I handled the html attributes and css correctly, so I would appreciate it if someone reviewed that part.
* Should we omit the detailed view when it is no more informative than the summary?

#### c2hs
c2hs

#### directory
directory

#### QuickCheck
quickcheck

### CODE REVIEW

**Comment by dcoutts** [comment]
Great stuff!


>  Where should the details go? Should we add an expander on the main package page so that users can toggle between the short and long dependency views? I'm not very familiar with generating webpages, so I would need help implementing this. We could instead link to a new page.

Yes, I think for the moment we should use a separate page. Perhaps later someone looking at page design can change some of these things to use expanders within the page.

> If the detailed view has its own page, should we modify the flags section, too? The main page could show only manual flags, and the detailed view could show the full table of flags.

Unfortunately "flags interesting to the user" and manual flags are orthogonal. There are interesting and uninteresting automatic flags, and interesting and uninteresting manual ones.

So for the moment I'd suggest just duplicating the flags table onto the detailed page.

> Should we add any other fields to the detailed view? I included buildable when it is false, because it explains why some branches have no dependencies.

I don't have any other suggestions yet. Is it easy to extend? Plausibly people might want build tools and C libs.

> I copied the formatting from the module tree. I'm not sure if I handled the html attributes and css correctly, so I would appreciate it if someone reviewed that part.

Looks ok from the screenshots. Will review more closely.

> Should we omit the detailed view when it is no more informative than the summary?

If we link to it anyway, is there any need to not link if there's no more detail?

Here's one other suggestion, if we've got more space now that it's on a separate page, perhaps one dep per line (rather than lots on each line) would be easier to read/scan.

**Comment by grayjay** [comment]
>> Should we add any other fields to the detailed view? I included buildable when it is false, because it explains why some branches have no dependencies.

> I don't have any other suggestions yet. Is it easy to extend? Plausibly people might want build tools and C libs.

I used `CondTree` to store the dependencies and buildable values directly, but we could easily add a data type with all fields of interest.

>> Should we omit the detailed view when it is no more informative than the summary?

> If we link to it anyway, is there any need to not link if there's no more detail?

> Here's one other suggestion, if we've got more space now that it's on a separate page, perhaps one dep per line (rather than lots on each line) would be easier to read/scan.

I like that idea.  It could even improve the readability of packages without executables or flags, so there is no reason to leave out the link.

Thanks for the feedback!  I will apply your suggestions when I have time, probably next week.

**Comment by grayjay** [comment]
@dcoutts, I updated the PR with your suggestions.  I'm not sure if I added the page correctly, since I'm new to the codebase.  I would be happy to refactor anything.  I also have a question.  To get the dependencies and flags, I called the function that generates the description for the main package page.  I noticed that that function queries the user database.  Is it worth refactoring the existing code to avoid the unneeded database access?

**Comment by dcoutts** [comment]
Ok, great, I'll try it out.

>  I noticed that that function queries the user database. Is it worth refactoring the existing code to avoid the unneeded database access?

No that's probably ok, reading these tables is very quick.

**Comment by dcoutts** [comment]
Merged. Thanks!

**Comment by grayjay** [comment]
@dcoutts I realized that this pull request conflicts with #357 .  Would you like me to rebase it if you haven't merged it yet?

**Comment by dcoutts** [comment]
Actually I confused myself, yes I re-merged #375. I'll try merging this one now manually. I'd like to do it now so I can get it deployed now, otherwise yes normally I'd take you up on your offer to rebase it for me.

**Comment by grayjay** [comment]
Thanks!

**Pull request merged**
