### PR TITLE
Add guidelines section to the front page

### PR DESCRIPTION
**Pull request by mightybyte**
This is an initial idea for solving issue #343 using a general guidelines section.

### CODE REVIEW

**Comment by dcoutts** [comment]
Looks sensible, I might tweak the wording a little to not annoy the PVP haters too much. e.g. "should" / "are recommended to" or something.

And good to advertise the candidates feature.

**Comment by bergmark** [comment]
I think pretty much everyone agrees on the rules for versioning right? Only upper bounds is a hot topic, so maybe it makes sense to keep "should" but put in a parenthical about pre-emptive upper bounds.

**Comment by dcoutts** [comment]
@bergmark right, or that. Suggestion?

**Comment by bergmark** [comment]
How about
```html
<li>All packages should follow the <a href="https://wiki.haskell.org/Package_versioning_policy">Package Versioning Policy (PVP), but note that there is no consensus on whether packages should have pre-emptive upper bounds on their dependencies</a>.</li>
```

**Comment by mightybyte** [comment]
This is not the place to point out items of disagreement.  People who disagree with the PVP should lobby for specific changes to it, not this.  This is just a pointer, and as such should not get into details at all.

**Comment by hvr** [comment]
I agree with @mightybyte here, we should try to keep this a simple pointer to the PVP page w/o diluting the waters... if there's a problem with PVP, it should be addressed at the source.

(and btw, a different more descriptive rather than normative take could be e.g. "Most packages follow the PVP", if "should" is really considered too strong -- which I don't think it is).

**Comment by gbaz** [comment]
Ditto, I vote to pull.

**Pull request merged**
